// <auto-generated />
namespace MapsProposal.Migrations.MapsProposalContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixlocationerror6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixlocationerror6));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101658020_fixlocationerror6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
